services:
  - type: web
    name: stb_emulator
    env: node
    buildCommand: |
      cd client && npm install && npm run build && cd .. && npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
