services:
  - type: static
    name: stb_emulator
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
